/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package se.team2.wowweather;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.EmptyBorder;
import se.team2.wowweather.classes.Constants;

public class AboutScreen extends javax.swing.JFrame {
    
    private Dimension wnd_dim = new Dimension(500, 320);

    /**
     * Creates new form AboutScreen
     */
    public AboutScreen() {
        
        this.setResizable(false);
        this.setTitle(Constants.TITLE_ABOUT_SCREEN);
        this.setPreferredSize(wnd_dim);
        
        // will hide the top bar with close button,
        // because we have a different button for closing
        this.setUndecorated(true);

        initComponents();
        this.setSize(wnd_dim);
        initComponentsOther();
    }
    
    /**
     *  Initializes content of the window.
     */
    private void initComponentsOther() {
        
        // background panel
        JPanel pnlBackground = new JPanel(new FlowLayout(FlowLayout.LEFT));       
        pnlBackground.setBackground(Color.white);
        pnlBackground.setSize(wnd_dim);
        pnlBackground.setMinimumSize(wnd_dim);
        pnlBackground.setBorder(BorderFactory.createMatteBorder(
            1, 1, 1, 1, Color.LIGHT_GRAY));
        
        // text content
        JLabel content = new JLabel();
        content.setFont(new java.awt.Font("Segoe UI", 0, 12));
        content.setBorder(new EmptyBorder(20, 20, 20, 20));
        
        String txt_content = "<html><body>";
        
        txt_content += "<b style=\"font-size:13px\">WowWeather</b><br>";
        txt_content += "Version: 1.0<br><br>";
        txt_content += "WowWeather is a free Windows Desktop application.<br>";
        txt_content += "It uses OpenWeather API for the weather reports.<br><br>";
        
        txt_content += "Source code available on GitHub repository:<br>" +
            "https://github.com/edgarspelna/ASPM-Team-2<br><br>";
        
        txt_content += "Software developed as part of " +
            "Applied Software Project Management course 16/17.<br>";
        txt_content += "<br>Authors: ";
        txt_content += "Edgars Pelna, Noman Ashraf, Sai Priyatham Dongoor,<br>" +
            "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" +
            "&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;" +
            "Syed Mudassir Mansoor Shah, Pengyang Qi, Shengjie Wang, Yuemin Zhao";
        
        txt_content += "</body></html>";
        content.setText(txt_content);
        
        pnlBackground.add(content);
        
        // FlowLayout for close button's row
        JPanel pnlButton = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        pnlButton.setSize(new Dimension(500, 50));
        pnlButton.setPreferredSize(new Dimension(470, 50));
        pnlButton.setBackground(Color.white);
        
        // close button
        JButton btn_close = new JButton();
        btn_close.setText("Close");
        // onclick: closes the window
        btn_close.addActionListener(new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                AboutScreen.this.dispose();
            }
        });
        pnlButton.add(btn_close);
        
        pnlBackground.add(pnlButton);
        pnlBackground.add(Box.createRigidArea(new Dimension(100, 10)));
        this.add(pnlBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(500, 300));
        setSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
